### ISSUE TITLE
a:5:{i:0;s:67:"Mage registry key "_singleton/localepackde/observer" already exists";i:1;s:1422:"#0 /var/www/vhosts/yourstool.nl/httpdocs/app/Mage.php(223): Mage::throwException('Mage registry k...')

### ISSUE THREAD

**Issue by yourstool** [riconeitzel/German_LocalePack_de_DE#169]
I installed the german language pack and then deinstalled it again.

After deinstalling returning to the admin page was impossible.

The error message reported is:
a:5:{i:0;s:67:"Mage registry key "_singleton/localepackde/observer" already exists";i:1;s:1422:"#0 /var/www/vhosts/yourstool.nl/httpdocs/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /var/www/vhosts/yourstool.nl/httpdocs/app/Mage.php(477): Mage::register('_singleton/loca...', false)
#2 /var/www/vhosts/yourstool.nl/httpdocs/app/code/core/Mage/Core/Model/App.php(1316): Mage::getSingleton('localepackde/ob...')
#3 /var/www/vhosts/yourstool.nl/httpdocs/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('adminhtml_contr...', Array)
#4 /var/www/vhosts/yourstool.nl/httpdocs/app/code/core/Mage/Adminhtml/Controller/Action.php(159): Mage::dispatchEvent('adminhtml_contr...', Array)
#5 /var/www/vhosts/yourstool.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Adminhtml_Controller_Action->preDispatch()
#6 /var/www/vhosts/yourstool.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('login')
#7 /var/www/vhosts/yourstool.nl/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/vhosts/yourstool.nl/httpdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/vhosts/yourstool.nl/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /var/www/vhosts/yourstool.nl/httpdocs/index.php(87): Mage::run('', 'store')
#11 {main}";s:3:"url";s:6:"/admin";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by yourstool** [comment]
Hi Rico,

I found the solution. Apparently the compilation was still on.
In this http://ebizmarts.com/forums/topics/view/2864 topic I found the solution:
Clear the cache
 ------------------
 SSH:
 find ./var/cache -type f -delete
 FTP: 
 mrm -r ./var/cache ; mkdir ./var/cache

 ------------------
Disable/Clear Magento compilation
 ------------------
 SSH:
 php -f shell/compiler.php -- disable
 php -f shell/compiler.php -- clear
 FTP:
 mv ./includes ./includes.unused


After that I was able to run the admin again.

WJ
